---

- name: Apt
  apt:
    name: "{{ item.apt | default(item.name) }}"
    state: "{{ item.state | default(package_state) }}"
    update_cache: "{{ package_update_cache }}"
    cache_valid_time: "{{ package_cache_valid_time }}"
  when: (item.apt_ignore|default('no'))|string in 'False,false,No,no'
  with_flattened:
    - "{{ package_list }}"
    - "{{ package_list_host }}"
    - "{{ package_list_group }}"
